# Docker Compose file for end-to-end testing
version: "3"

networks:
  skema_net:
    external: true

services:

  # FIXME start the mathjax service and set dependencies such that
  # it is run before any other service

  img2mml:
    image: lumai/askem-skema-img2mml:latest
    container_name: img2mml
    entrypoint: uvicorn img2mml:app --host=0.0.0.0 --port=8020
    ports:
      - "8020:8020"
    networks:
      skema_net:
        aliases:
          - "img2mml" 

  latex2mml:
    image: lumai/askem-skema-img2mml:latest
    container_name: latex2mml
    entrypoint: uvicorn latex2mml:app --host=0.0.0.0 --port=8030
    ports:
      - "8030:8030"
    networks:
      skema_net:
        aliases:
          - "latex2mml" 

