# Docker Compose file for skema services
version: "3.9"

services:

  mit-tr:
    image: chunwei/mitaskem-api:latest
    ports:
      - "9010:8000"

  skema-tr:
    image: lumai/askem-skema-text-reading:latest
    ports:
      - "9000:9000"
    environment:
      APPLICATION_SECRET: 8c2fb5a58ae8d9ec6f7065a25c35aac2
      SKEMA_HOSTNAME: skema.clulab.org
      _JAVA_OPTIONS: -Xmx10g -Xms10g -Dfile.encoding=UTF-8

  jupyter:
    image: lumai/askem-skema-py:latest
    container_name: jupyter
    ports:
      - "7777:7777"
    command: jupyter notebook --no-browser --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password='' --port=7777 /data/notebooks
    volumes:
      - ./data/:/data/skema
      - ./notebooks:/data/notebooks

  skema-py:
    image: lumai/askem-skema-py:latest
    container_name: skema-py
    ports:
      - "8000:8000" # Change port mapping appropriately before deploying.
    # open browser to http://localhost:8000/docs
    environment:
      - "SKEMA_RS_ADDESS=skema-rs:8080"
      - "SKEMA_TR_ADDRESS=http://skema-tr:9000"
      - "SKEMA_MATHJAX_ADDRESS=http://mathjax:8031"
      - "OPENAI_KEY=DONT_FORGET_UR_KEY"
      
    command: ["uvicorn", "skema.rest.api:app", "--host", "0.0.0.0", "--port", "8000"]

  skema-rs:
    image: lumai/askem-skema-rs:latest
    container_name: skema-rs
    entrypoint: ./target/release/skema_service --host 0.0.0.0 --port 8080 --db-host graphdb
    ports:
      - "8080:8080"

  # We currently use Memgraph (in-memory graph database).
  graphdb:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH=--memory-limit=3000 --log-level=TRACE"

  # example cmd: curl -X POST http://0.0.0.0:8031/tex2mml \
  # -H "Content-Type: application/json" \
  # -d '{"tex_src": "E = mc^{2}"}'
  mathjax:
    #image: lumai/askem-skema-py:latest
    # ... or to build locally:
    image: lumai/askem-skema-py:latest
    environment:
      - "SKEMA_MATHJAX_HOST=0.0.0.0"
      - "SKEMA_MATHJAX_PORT=8031"
    ports:
      - "8031:8031"
    working_dir: /app/skema/img2mml/data_generation
    entrypoint: [ "npm", "start" ]

volumes:
  mg_lib:
  mg_log:
  mg_etc:
