# Docker Compose file for skema services
version: "3"

networks:
  skema_net:
    external: true

services:

  skema-rs:
    image: lumai/askem-skema-rs:latest
    container_name: skema-rs
    entrypoint: cargo run --release --bin skema_service -- --host 0.0.0.0 --db-host database
    ports:
      - "8080:8080"
    networks:
      skema_net:
        aliases:
          - "skema-rs"  # use ${AGENT_NAME} before deploying
  database:
    image: "memgraph/memgraph-platform"
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH="--log-level=TRACE"
    entrypoint: ["/usr/bin/supervisord"]

volumes:
  mg_lib:
  mg_log:
  mg_etc:
