# Docker Compose file for end-to-end testing
version: "3"

networks:
  skema_net:
    external: true

services:

  # FIXME start the mathjax service and set dependencies such that
  # it is run before any other service

  img2mml:
    image: lumai/askem-skema-py:latest
    container_name: skema-py
    entrypoint: uvicorn skema.skema_py.server:app --host=0.0.0.0 --port=8030
    ports:
      - "8030:8030"
    networks:
      skema_net:
        aliases:
          - "skema-py" 

  mathjax:
    image: lumai/askem-skema-py:latest
    container_name: mathjax
    entrypoint: uvicorn latex2mml:app --host=0.0.0.0 --port=8031
    ports:
      - "8031:8031"
    networks:
      skema_net:
        aliases:
          - "mathjax" 

